### ISSUE TITLE
Download: --rename and --out-dir are mutually exclusive

### ISSUE THREAD

**Issue by bede** [GlobalPathogenAnalysisService/gpas-cli#111]
```
% gpas download --environment dev --rename --mapping-csv E-39dc5633.mapping.csv --out-dir ~/Desktop/oot --file-types fasta tests/test-data/token.json
Querying status for 4 sample(s): 100%|█████████████████████████████████████| 4/4
INFO: Fetching file types ['fasta']
Downloading 4 files for 4 sample(s):   0%|                                 | 0/4Traceback (most recent call last):
  File "/Users/bede/Research/Git/gpas-cli/src/gpas/lib.py", line 246, in download_async
    return [
  File "/Users/bede/Research/Git/gpas-cli/src/gpas/lib.py", line 247, in <listcomp>
    await f
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/site-packages/tenacity/_asyncio.py", line 86, in async_wrapped
    return await fn(*args, **kwargs)
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/site-packages/tenacity/_asyncio.py", line 48, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/site-packages/tenacity/__init__.py", line 351, in iter
    return fut.result()
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/site-packages/tenacity/_asyncio.py", line 51, in __call__
    result = await fn(*args, **kwargs)
  File "/Users/bede/Research/Git/gpas-cli/src/gpas/lib.py", line 284, in download_single_async
    update_fasta_header(
  File "/Users/bede/Research/Git/gpas-cli/src/gpas/lib.py", line 116, in update_fasta_header
    with gzip.open(path, "rt") as fh:
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/gzip.py", line 174, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '00c5bc2d-c95e-1b19-4053-0ae49b5d69a0.fasta.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/bin/gpas", line 8, in <module>
    sys.exit(main())
  File "/Users/bede/Research/Git/gpas-cli/src/gpas/cli.py", line 271, in main
    defopt.run(
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/site-packages/defopt.py", line 356, in run
    return call()
  File "/Users/bede/Research/Git/gpas-cli/src/gpas/cli.py", line 259, in download
    asyncio.run(
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/bede/Research/Git/gpas-cli/src/gpas/lib.py", line 229, in download_async
    async with httpx.AsyncClient(transport=transport, timeout=120) as client:
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/site-packages/httpx/_client.py", line 2003, in __aexit__
    await self._transport.__aexit__(exc_type, exc_value, traceback)
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/site-packages/httpx/_transports/default.py", line 332, in __aexit__
    await self._pool.__aexit__(exc_type, exc_value, traceback)
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 326, in __aexit__
    await self.aclose()
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 312, in aclose
    raise RuntimeError(
RuntimeError: The connection pool was closed while 2 HTTP requests/responses were still in-flight.
Downloading 4 files for 4 sample(s):   0%|                                 | 0/4
ERROR: Task exception was never retrieved
future: <Task finished name='Task-16' coro=<download_single_async() done, defined at /Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/site-packages/tenacity/_asyncio.py:84> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/site-packages/tenacity/_asyncio.py", line 86, in async_wrapped
    return await fn(*args, **kwargs)
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/site-packages/tenacity/_asyncio.py", line 48, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/site-packages/tenacity/__init__.py", line 351, in iter
    return fut.result()
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/site-packages/tenacity/_asyncio.py", line 51, in __call__
    result = await fn(*args, **kwargs)
  File "/Users/bede/Research/Git/gpas-cli/src/gpas/lib.py", line 284, in download_single_async
    update_fasta_header(
  File "/Users/bede/Research/Git/gpas-cli/src/gpas/lib.py", line 116, in update_fasta_header
    with gzip.open(path, "rt") as fh:
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/gzip.py", line 174, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '0537ce51-866e-a6b9-0601-9c775fd74fb3.fasta.gz'
(gpas-cli-dev) bede@zizzle gpas-cli % 
```

**Comment by bede** [comment]
Fixed https://github.com/GlobalPathogenAnalysisService/gpas-cli/commit/9f5dd89bea0bdd4ac48c9a7ec3c0192bdc32da3b
