### ISSUE TITLE
PyInstaller builds failing with PyInstaller >= 5.6.2

### ISSUE THREAD

**Issue by bede** [GlobalPathogenAnalysisService/gpas-cli#114]
Pinned 5.6.2

**Comment by bede** [comment]
Ubuntu 22.04LTS in actions

```
Run dist/gpas upload tests/test-data/large-illumina-bam.csv --processes 2
  dist/gpas upload tests/test-data/large-illumina-bam.csv --processes 2
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.9/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.9/x64/lib
Traceback (most recent call last):
  File "gpas/cli.py", line 9, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "pandas/__init__.py", line 22, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "pandas/compat/__init__.py", line 18, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "pandas/compat/numpy/__init__.py", line 4, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "pandas/util/__init__.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "pandas/core/util/hashing.py", line 17, in <module>
ImportError: cannot import name 'lib' from 'pandas._libs' (/tmp/_MEIhHQ3k2/pandas/_libs/__init__.pyc)
[5793] Failed to execute script 'cli' due to unhandled exception!
Error: Process completed with exit code 1.
```
