### ISSUE TITLE
collection_date error in tip of main

### ISSUE THREAD

**Issue by bede** [GlobalPathogenAnalysisService/gpas-cli#54]
Does not affect releases
```
(gpas-cli-dev) bede@yoshina gpas-cli % gpas upload tests/test-data/large-nanopore-bam.csv --environment staging --token /Users/bede/Downloads/token\(2\).json 
INFO: Validation successful
INFO: Using 12 processes
INFO: Finished converting 1 sample(s)                                           
INFO: Finished decontaminating 1 sample(s)                                      
INFO: Saved mapping CSV to A-c24864c8.mapping.csv
INFO: Finished uploading 1 sample(s)                                            
Traceback (most recent call last):
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/bin/gpas", line 33, in <module>
    sys.exit(load_entry_point('gpas', 'console_scripts', 'gpas')())
  File "/Users/bede/Research/Git/gpas-cli/src/gpas/cli.py", line 249, in main
    defopt.run(
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/site-packages/defopt.py", line 275, in run
    return func(*ba.args, **ba.kwargs)
  File "/Users/bede/Research/Git/gpas-cli/src/gpas/cli.py", line 115, in upload_wrapper
    jsonify_exceptions(
  File "/Users/bede/Research/Git/gpas-cli/src/gpas/misc.py", line 117, in jsonify_exceptions
    return function(**kwargs)
  File "/Users/bede/Research/Git/gpas-cli/src/gpas/cli.py", line 88, in upload
    batch.upload(dry_run=dry_run)
  File "/Users/bede/Research/Git/gpas-cli/src/gpas/lib.py", line 823, in upload
    self._submit()
  File "/Users/bede/Research/Git/gpas-cli/src/gpas/lib.py", line 759, in _submit
    self._prepare_submission()
  File "/Users/bede/Research/Git/gpas-cli/src/gpas/lib.py", line 777, in _prepare_submission
    "collection_date": str(s.collection_date.date()),
AttributeError: 'str' object has no attribute 'date'
```

**Comment by bede** [comment]
Fixed https://github.com/GlobalPathogenAnalysisService/gpas-cli/commit/756dc838ff42829f116300b7d4a3583da71ac34e
