### ISSUE TITLE
SubmissionError with country code CYM

### ISSUE THREAD

**Issue by bede** [GlobalPathogenAnalysisService/gpas-cli#55]
This appears to be an API error, not a gpas-cli issue

```
(gpas-cli-dev) bede@yoshina gpas-cli % gpas upload --environment staging --token tests/test-data/token-staging.json tests/test-data/cayman.csv
INFO: Validation successful
INFO: Using 12 processes
INFO: Finished decontaminating 1 sample(s)                                                                                                                                                      
INFO: Saved mapping CSV to D-843ea7fc.mapping.csv
INFO: Finished uploading 1 sample(s)                                                                                                                                                            
Traceback (most recent call last):
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/bin/gpas", line 33, in <module>
    sys.exit(load_entry_point('gpas', 'console_scripts', 'gpas')())
  File "/Users/bede/Research/Git/gpas-cli/src/gpas/cli.py", line 249, in main
    defopt.run(
  File "/Users/bede/miniconda3/envs/gpas-cli-dev/lib/python3.10/site-packages/defopt.py", line 275, in run
    return func(*ba.args, **ba.kwargs)
  File "/Users/bede/Research/Git/gpas-cli/src/gpas/cli.py", line 115, in upload_wrapper
    jsonify_exceptions(
  File "/Users/bede/Research/Git/gpas-cli/src/gpas/misc.py", line 117, in jsonify_exceptions
    return function(**kwargs)
  File "/Users/bede/Research/Git/gpas-cli/src/gpas/cli.py", line 88, in upload
    batch.upload(dry_run=dry_run)
  File "/Users/bede/Research/Git/gpas-cli/src/gpas/lib.py", line 824, in upload
    self._submit()
  File "/Users/bede/Research/Git/gpas-cli/src/gpas/lib.py", line 761, in _submit
    self._finalise_submission()
  File "/Users/bede/Research/Git/gpas-cli/src/gpas/lib.py", line 742, in _finalise_submission
    raise misc.SubmissionError(r.json().get("errorMsg"))
gpas.misc.SubmissionError: Error occurred creating samples: Invalid sample country: CYM
```

**Comment by bede** [comment]
Confirmed upstream https://oc-collab.gc3.ocs.oraclecloud.com/browse/C900000008-802

**Comment by bede** [comment]
Fixed upstream
